# Generated by Django 5.2 on 2025-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='menu_items/default.jpg', null=True, upload_to='menu_items/'),
        ),
    ]
